/vis/open OGL 800x800-0+0

/vis/drawVolume
/vis/viewer/set/viewpointThetaPhi 180. 0.
/vis/viewer/zoom 30.
/vis/viewer/set/style wireframe
/vis/scene/add/axes 0 0 0 1 m
/vis/scene/add/trajectories "rich smooth"
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
/vis/scene/add/hits



