#!/bin/bash


run=615
N0=39800
Nevents=10000000
Nsim=500000
#root -l -b -q "scripts/DC_occupancy2.cxx($run,$N0,$Nevents,$Nsim)"
root -l -b -q "scripts/DC_occupancy_sectors.cxx($run,$N0,$Nevents,$Nsim)"
#root -l -b -q "scripts/DC_occupancy_source.cxx($run,$N0,$Nevents,$Nsim)"

run=815
N0=22100
Nevents=10000000
Nsim=500000
#root -l -b -q "scripts/DC_occupancy2.cxx($run,$N0,$Nevents,$Nsim)"
root -l -b -q "scripts/DC_occupancy_sectors.cxx($run,$N0,$Nevents,$Nsim)"
#root -l -b -q "scripts/DC_occupancy_source.cxx($run,$N0,$Nevents,$Nsim)"

run=1115
N0=129700
Nevents=10000000
Nsim=500000
#root -l -b -q "scripts/DC_occupancy2.cxx($run,$N0,$Nevents,$Nsim)"
root -l -b -q "scripts/DC_occupancy_sectors.cxx($run,$N0,$Nevents,$Nsim)"
#root -l -b -q "scripts/DC_occupancy_source.cxx($run,$N0,$Nevents,$Nsim)"

#root "scripts/DC_occupancy2.cxx(815,22100,1000000)"
#root "scripts/DC_occupancy_sectors.cxx(815,22100,1000000)"
#root "scripts/DC_occupancy_source.cxx(815,22100,1000000)"
#
#root "scripts/DC_occupancy2.cxx(1115,129700,1000000)"
#root "scripts/DC_occupancy_sectors.cxx(1115,129700,1000000)"
#root "scripts/DC_occupancy_source.cxx(1115,129700,1000000)"
